# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_image_info": "01_voc2coco.ipynb",
         "get_coco_annotation_from_obj": "01_voc2coco.ipynb",
         "convert_xmls_to_cocojson": "01_voc2coco.ipynb",
         "convert_coordinate": "02_coco2yolo.ipynb",
         "convert": "02_coco2yolo.ipynb"}

modules = ["voc2coco.py",
           "coco2yolo.py"]

doc_url = "https://chienlm297.github.io/annos_conversion/"

git_url = "https://github.com/chienlm297/annos_conversion/tree/master/"

def custom_doc_links(name): return None
